apiVersion: apps/v1
kind: Deployment
metadata:
  name: web1
  labels:
    app: web1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web1
  template:
    metadata:
      labels:
        app: web1
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '3000'
    spec:
      containers:
      - name: web1
        image: <aws_account_id>.dkr.ecr.<region>.amazonaws.com/web1:<tag>
        imagePullPolicy: Always # Ensure this is set to Always
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            cpu: "250m"
            memory: "128Mi"
      - name: fluent-bit
        image: fluent/fluent-bit:3.1
        imagePullPolicy: Always # Ensure this is set to Always
        ports:
        - containerPort: 24224
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
          requests:
            memory: "64Mi"
            cpu: "125m"
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        env:
        - name: FLUENT_ELASTICSEARCH_HOST
          value: "logs.example.com"
        - name: FLUENT_ELASTICSEARCH_PORT
          value: "443"
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
---
apiVersion: v1
kind: Service
metadata:
  name: web1
spec:
  type: NodePort
  ports:
  - port: 81
    targetPort: 5000
    nodePort: 30081 # Define your own NodePort or let Kubernetes assign one  
  selector:
    app: web1
